SCREEN_WIDTH, SCREEN_HEIGHT = 1024, 768
FPS = 60

WHITE = (255, 255, 255)
EGG_WHITE = (240, 240, 220)
BLACK_GREY = (50, 50, 50)
BLACK = (0, 0, 0)
MIDNIGHT_BLUE = (25, 25, 80)
DENIM_BLUE = (15, 16, 54)
LIGHT_BLUE = (96, 216, 232)
DARK_BLUE = (0, 128, 255)
ORANGE = (255, 165, 0)
YELLOW = (255, 255, 0)
GREEN = (50, 205, 50)
RED = (255, 0, 0)
MAGENTA = (255, 0, 255)

COLORS = [MIDNIGHT_BLUE, LIGHT_BLUE, DARK_BLUE, ORANGE, YELLOW, GREEN, RED, MAGENTA]

GRID_ROWS = 22
GRID_COLS = 10
GRID_CELL_SIZE = 30

# Info rect
INFO_RECT_X = SCREEN_WIDTH / 2 + (GRID_COLS + 2) * GRID_CELL_SIZE / 2
INFO_RECT_Y = SCREEN_HEIGHT / 2 + 2 * GRID_CELL_SIZE
INFO_RECT_WIDTH = 8 * GRID_CELL_SIZE
INFO_RECT_HEIGHT = 9 * GRID_CELL_SIZE

# Next blocks rect
NEXT_RECT_X = SCREEN_WIDTH / 2 + (GRID_COLS + 2) * GRID_CELL_SIZE / 2
NEXT_RECT_Y = SCREEN_HEIGHT / 2 - 9 * GRID_CELL_SIZE
NEXT_RECT_WIDTH = 8 * GRID_CELL_SIZE
NEXT_RECT_HEIGHT = 10 * GRID_CELL_SIZE

# Stored block rect
STORED_RECT_X = SCREEN_WIDTH / 2 - (GRID_COLS + 18) * GRID_CELL_SIZE / 2
STORED_RECT_Y = SCREEN_HEIGHT / 2 - 9 * GRID_CELL_SIZE
STORED_RECT_WIDTH = 8 * GRID_CELL_SIZE
STORED_RECT_HEIGHT = 8 * GRID_CELL_SIZE

# Combo rect
COMBO_RECT_X = SCREEN_WIDTH / 2 - (GRID_COLS + 18) * GRID_CELL_SIZE / 2
COMBO_RECT_Y = SCREEN_HEIGHT / 2 + 0 * GRID_CELL_SIZE
COMBO_RECT_WIDTH = 8 * GRID_CELL_SIZE
COMBO_RECT_HEIGHT = 5 * GRID_CELL_SIZE

# Lines cleared rect
LINES_RECT_X = SCREEN_WIDTH / 2 - (GRID_COLS + 18) * GRID_CELL_SIZE / 2
LINES_RECT_Y = SCREEN_HEIGHT / 2 + 6 * GRID_CELL_SIZE
LINES_RECT_WIDTH = 8 * GRID_CELL_SIZE
LINES_RECT_HEIGHT = 5 * GRID_CELL_SIZE
